# -*- coding: utf-8 -*-
"""Gearbox_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieys5gouZG1O6O14I5p1D8MERT3onxLu
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("Gearbox_failure_prediction.pkl")

st.title("Wine Type Prediction!")

Load_%= st.input["Load_%"]
Temperature_C = st.input["Temperature_C"]
Oil_Level_% = st.input["Oil_Level_%"]
Vibration_mm_s = st.input["Vibration_mm_s"]


df = pd.DtaFrame({
"Load_%": [Load_%],
"Temperature_C": [Temperature_C],
"Oil_Level_%": [Oil_Level_%],
"Vibration_mm_s": [Vibration_mm_s]
})

if st.button("Predict Gearbox Failure Segmentation"):
  prediction = model.predict(df)[0]
