# -*- coding: utf-8 -*-
"""Gearbox_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieys5gouZG1O6O14I5p1D8MERT3onxLu
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("Gearbox_failure_prediction.pkl")

st.title("Gearbox Failure Prediction")

Load = st.number_input("Load (%)")
Temperature = st.number_input("Temperature (°C)")
Vibration = st.number_input("Vibration (mm/s)")
Oil_Level = st.number_input("Oil Level (%)")


input_data = pd.DataFrame({
    'Load_%': [Load],
    'Temperature_C': [Temperature],
    'Vibration_mm_s': [Vibration],
    'Oil_Level_%': [Oil_Level]
})
if st.button("Predict Gearbox Failure Segmentation"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("Gear Failure Predicted")
    else:
        st.success("No Gear Failure Predicted")
